### ISSUE TITLE
Meta-issue: The road to production

### ISSUE THREAD

**Issue by premist** [premist/pusuq.rb#1]
This issue tracks all necessary requirements for using Pusuq in production.

- [ ] [Pub/Sub gRPC API](https://cloud.google.com/pubsub/docs/reference/rpc/) exits alpha
- [ ] Pub/Sub service on [google-cloud-ruby](https://github.com/GoogleCloudPlatform/google-cloud-ruby/) becomes GA
- [ ] Pusuq has all necessary unit test ready
- [ ] Pusuq has minimal end-to-end test ready
